services:
  web:
    build:
      context: .
    container_name: django_app
    volumes:
      - .:/code
      - ./secrets/gcs-creds.json:/secrets/gcs-creds.json:ro
    working_dir: /code
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - NVIDIA_VISIBLE_DEVICES=all
      - GOOGLE_APPLICATION_CREDENTIALS=/secrets/gcs-creds.json
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]


  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
