# Generated by Django 5.2.1 on 2025-06-10 11:40

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBackMusic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promptfeed', models.TextField(max_length=500, verbose_name='prompt')),
                ('rate', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='rate')),
                ('reward', models.FloatField(default=0.0, verbose_name='reward')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MusicGenerated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField(max_length=500, verbose_name='prompt')),
                ('music', models.FileField(upload_to='music/', verbose_name='music')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MidiSentByUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('midi_file', models.FileField(upload_to='midis/', verbose_name='midi file')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_midis', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
